### ISSUE TITLE
UWP games may not be found 

### ISSUE THREAD

**Issue by Codeusa** [RainwayApp/bug-tracker#1]
Currently we look for the Windows Store cache on the users PC to detect game installs, however this cache is cleared by the Windows Store itself meaning installed games might not be found.

The user has to go to the games Window Store page for the cache file to be redownloaded and for Rainway to find the game. We need to improve this lookup to not rely on these cached files.

**Comment by BetaLeaf** [comment]
## Powershell Commands

Get the list of installed UWP Apps:
```Get-AppXPackage```

Launch UWP App:
```Start-Process Shell:AppsFolder\<PackageFamilyName>!App```

Here's an example for Minecraft:
![image](https://user-images.githubusercontent.com/7028351/35341487-d09544c2-00f3-11e8-8954-9057a0f7f6c6.png)

More Info:
https://docs.microsoft.com/en-us/powershell/module/appx/get-appxpackage?view=win10-ps
https://docs.microsoft.com/en-us/uwp/api/Windows.Management.Deployment.PackageManager

**Comment by BetaLeaf** [comment]
https://docs.microsoft.com/en-us/windows/uwp/monetize/get-product-info-for-apps-and-add-ons

**Comment by Lazermn03** [comment]
I've used that in the past, but Shadows of War doesn't show up the list like Minecraft, Forza, and others.

**Comment by Lazermn03** [comment]
The folder structure for Shadows of War is different than other games in the WindowsApps directory. You also can't launch the EXE directly. I think it's some new sort of DRM MS has put in place.

**Comment by Codeusa** [comment]
We don't launch executable directly, look at our Warden project. The issue is likely an exception being thrown by game scanning itself and I am going to rewrite a big chunk of this today.

**Comment by Lazermn03** [comment]
Sounds good. @Codeusa. I did find that it's called WarnerBros.Interactive.WB-Kraken in the AppXPackage, but I couldn't get it to launch anyway I tried with the start-process commandlet.

**Comment by Jessomadic** [comment]
@Lazermn03 Worse come to Worse. There are bypasses online for that new DRm that MS has put on their games

**Comment by Lazermn03** [comment]
The lag is too bad in Rainway still for me to seriously use it, but it doesn't show up in Moonlight either. I have to launch the desktop and then open Shadow of War to play it.

**Comment by BetaLeaf** [comment]
@Lazermn03 Take a look at the comment above. I posted a picture with an example on launching Minecraft from powershell. https://github.com/RainwayApp/bug-tracker/issues/1#issuecomment-360177984

**Comment by Lazermn03** [comment]
Yeah, I tried that like I have for games like Minecraft and Forza, but it doesn't work. It says the app cannot be found.

**Comment by Massamo** [comment]
uses a program called UWPHook it will add them to steam

**Comment by healingbrew** [comment]
Should be fixed in the next update.
