### ISSUE TITLE
steam URL is not displayed

### ISSUE THREAD

**Issue by hiccups1980** [RainwayApp/bug-tracker#10]
Rainway asks you to fill in your steam username and password.
I think there is a way to link the steam account without giving rainway my login data (see steam API). GOG did that successfully with my steam account. And it did NOT ask me what my password is.
And in the login window it doesn't display the URL I'm logging into.

I think that is a security issue for a lot of steam users.

**Comment by Codeusa** [comment]
We are using the steam OpenID login portal, this is not an issue.

**Comment by hiccups1980** [comment]
If you are using the steam portal than display the URL in the window, so we know that it is the real portal. Or open the page in the browser for us to see the URL.

You know how phishing sites clone login sites?

**Comment by IkeKap** [comment]
Just for future reference, how would one tell (on another piece of software) whether a steam login is being routed through legitimate means such as the openID portal versus more nefarious portals @Codeusa ?

**Comment by Codeusa** [comment]
@IkeKap it tells you the URL before it rewrites it to the title of the page.
