### ISSUE TITLE
Gameplay is different

### ISSUE THREAD

**Issue by swpendo** [RainwayApp/bug-tracker#101]
Instead of streaming a game using the internet, the game boots up from the file instead!

**Comment by Jessomadic** [comment]
The point of Rainway is that it takes the install of a game on one PC and will stream it to a new PC not the Host PC (The One you put the Server on). This is so you can grab a Chromebook (or something just as weak) and run windows games on it at full resolution and Framerate. But the game has to be installed to do this. You do not run it on the computer with the server unless there is testing that you are doing

**Comment by Jessomadic** [comment]
Is this what you mean? If so please close the thread. And if not please explain it to me.

**Comment by healingbrew** [comment]
Marking issue as resolved.

**Comment by Jessomadic** [comment]
Thanks
