### ISSUE TITLE
Not able to connect from another computer in the same network, if the said network has no internet

### ISSUE THREAD

**Issue by sperrichon** [RainwayApp/bug-tracker#102]
Hi,

As the title says, I wouldn't be able to connect from another computer, (I wouldn't even be able to get a certificate on the server), if the server or the client browser are on the same network, but that network is not connected to Internet.

Because I'm frequently moving my PC to places where there is an ethernet switch, but no decent internet, it would be cool to be able to just power the PC and plug it, and use a laptop to play the games.

It's more like a 'direct-link/offline' feature request than a bug.

**Comment by Jessomadic** [comment]
When you say "Offline" do you mean the ability to use Rainway with no internet?

**Comment by Codeusa** [comment]
The computer needs internet so we can validate connections as legitimate.

**Comment by sperrichon** [comment]
Yes I meant the ability to use Rainway with no internet. I believe there would be no validation involved with any external server then: a direct connection with no passthrough, no reverse proxies.

**Comment by sperrichon** [comment]
I don't care if I had to generate a fake CA cert and add it to the trusted certs of each computer
