### ISSUE TITLE
Possibility of bundling Rainway with other codeusa projects

### ISSUE THREAD

**Issue by IkeKap** [RainwayApp/bug-tracker#106]
It would be cool if people could pick at installation whether they also want to install ulterius and Borderless gaming along with rainway.

This is an enhancement not a bug or anything

**Comment by BetaLeaf** [comment]
Yea, no. Please don't do this. Most people hate bundleware, including me. If people want to download these extras, they will google for them and download it themselves.

**Comment by IkeKap** [comment]
It could be off by default, I was just throwing around an idea

**Comment by Jessomadic** [comment]
Have to side with BetaLeaf here. Bundleware is annoying and can make is so people end up with stuff they don't want even if it is off by default

**Comment by BetaLeaf** [comment]
Also, some anti virus vendors will flag your executable if you have bundleware in your installer. As someone who is a software engineer, I constantly have to fight with them to get my executables whitelisted and I don't have bundleware in my installers, so I can only imagine how much of a pain it would be for the Rainway Team if they included these practices in their app. 

I think the best way to do this would simply have a link to their website at the end of the installation wizard, where they can check out their other software.

**Comment by healingbrew** [comment]
lol no
