### ISSUE TITLE
Describe the issue

### ISSUE THREAD

**Issue by imvudude** [RainwayApp/bug-tracker#107]
Bug ID: 4d01c260-4e46-4572-9c42-fb37aefa914e
Steps to reproduce the problem:
Start up rainway, try to connect on an android device, receive socket connection failed: 1006, desktop client restarts independently of that issue, then crash

What is the expected behavior?
the rainway client should stay openand connect

What went wrong?
it restarted a few times and then crashed

Did this work before?
not really, no

Does this work in other browsers?
Haven't gotten to that part yet

OS Info: Windows 10 Home x64 [10.0.16299]

Rainway Server Version: 0.1.13.0

Rainway Frontend Version: 1.0.2.0

**Comment by BetaLeaf** [comment]
Update Rainway to 0.1.15 and try again. They should have fixed this issue on 0.1.15.
[https://releases.rainway.io/Installer_0.1.15.exe](https://releases.rainway.io/Installer_0.1.15.exe)

**Comment by healingbrew** [comment]
closing until issue is proven to persist
