### ISSUE TITLE
Describe the issue

### ISSUE THREAD

**Issue by AngelSora** [RainwayApp/bug-tracker#112]
Bug ID: 5bc0c6d7-fb86-4a93-9f6f-96f74cbf5e34
Steps to reproduce the problem:

What is the expected behavior?

What went wrong?

Did this work before?

Does this work in other browsers?

OS Info: Windows 10 Professional x64 [10.0.16299]

Rainway Server Version: 0.1.0.0

Rainway Frontend Version: 1.0.2.0

**Comment by Jessomadic** [comment]
Are you having an issue?

**Comment by olivieralvespro** [comment]
i think we can close this

**Comment by Jessomadic** [comment]
Yeah. Seconded

**Comment by Jessomadic** [comment]
@Codeusa can you help with that
