### ISSUE TITLE
Rainway doesn't see my steam games.

### ISSUE THREAD

**Issue by mixon606** [RainwayApp/bug-tracker#132]
Rainway can't see my steam games
![rainwaykurwa steama nje widzi](https://user-images.githubusercontent.com/35871306/35473218-c67ee0ac-037c-11e8-9928-b3fe2fffdd84.PNG)

**Comment by Codeusa** [comment]
Does clicking the refresh button at the top help?

**Comment by mixon606** [comment]
no

**Comment by fofwisdom** [comment]
No.

**Comment by rmogstad** [comment]
Same for me.  Clicking refresh does not help, clearing cache does not help.

**Comment by healingbrew** [comment]
Duplicate of #120
