### ISSUE TITLE
Server can't ve installed again if files are manually deleted

### ISSUE THREAD

**Issue by animekai** [RainwayApp/bug-tracker#139]
I couldn't find the uninstaller for rainway, so I delete the files manually, but now I can't install it back, it said I have installed the newer version, but I erased the files even from documents folder, and applocal data and nothing, the only way I could install it was to wait for a new update and download the new installer, that was a solution for now, pls make an dedicated uninstaller

**Comment by Codeusa** [comment]
You could have uninstalled it from the program menu or the shortcut that says "Remove Rainway".

You'll need to use a 3rd party tool to delete it like Revo Uninstaller
