### ISSUE TITLE
Display generic or substitute banner for games not registered

### ISSUE THREAD

**Issue by azumukupoe** [RainwayApp/bug-tracker#145]
We should have access to every games in our library.

**Comment by Jessomadic** [comment]
It is quite easy to play a game that rainway has not detected. Use @betaleaf desktop mode. He wrote it himself. It’s in quite a few of the threads if you can find it. I will look for it when I have a chance.

**Comment by BetaLeaf** [comment]
Here you go! https://github.com/RainwayApp/bug-tracker/issues/63#issuecomment-360223463
I'd recommend doing what @healingbrew says as well. https://github.com/RainwayApp/bug-tracker/issues/63#issuecomment-360224124
"I suggest using the name "Remote Desktop" as we have a dummy "game" metadata entry for that name."

**Comment by healingbrew** [comment]
The issue isn't that they don't have a banner. We already support games that don't have a banner. It's that for some reason our API cannot find the game.

I will start an issue where I can keep track of missing games.
