### ISSUE TITLE
nVidia Lag using Rainway encoder

### ISSUE THREAD

**Issue by jimmiemaul** [RainwayApp/bug-tracker#148]
**Server Information**
Windows 10 1709 Professional 64bit
nVidia GeForce GTX 960
Intel i5-4460
12GB RAM
Internet speed: 40MB Down / 10MB Up

**Rainway Config**
Screen Scaled to 1280x720
FPS: 30
Bitrate: 2% CBR

**Client Information**
Windows 7 Enterprise 64bit
Intel i7-4600
16GB RAM
Chrome Beta 64.0.3282.119
Connected via Websocket
Internet Speed: 100mb down / 100mb up

---

When playing rocket league, experiencing intermittent stutters, and slow response of keypresses (around 50ms)

Client reports 23ms latency but feels way slower than that. 
Logs of sessions attached

[Logs.zip](https://github.com/RainwayApp/bug-tracker/files/1685814/Logs.zip)

**Comment by Codeusa** [comment]
30 FPS means up to 33ms of latency at a minimum. If you want low latency you need 60 FPS. In addition you might see better performance using Quality mode set to like 25%.

**Comment by jimmiemaul** [comment]
Thanks for the suggestion. I'll do some tinkering and will report back.

**Comment by jimmiemaul** [comment]
Stuttering caused by internal network. When host and client wired directly to router, stuttering not observed.

Power line adapter causing spikes, have now placed these firmly into the bin.

**Comment by jimmiemaul** [comment]
Still getting issues with this. Current setup is the client laptop listed in the original comment, wired directly to the router, which is directly wired into the server via ethernet cables.

Lag observed when playing Rocket League and CSGO as these are the two games I tested with. I believe this will happen to any game I run. On screen latency on the client end listed as 3ms. Below are links to videos showing client laptop, and server desktop doing the same actions

Tried using Quality 20%, and Bitrate 10Mbps but same issues encountered. FPS 60 and no screen scaling.

On the client video, you can actually hear me doing the keypresses for turning the car left and right, and the delay between them happening on stream.

https://photos.app.goo.gl/iAD4VXZ5lkMgvGEf2

Also attached logs below

[Logs.zip](https://github.com/RainwayApp/bug-tracker/files/1708438/Logs.zip)

Any help received would be greatly appreciated. I use Steam In-Home streaming with exactly the same client and server machines and they work perfectly.

**Comment by jimmiemaul** [comment]
Below are two images. One of the client running Rainway, showing performance monitor. No real spiking or topping out while stutters occurring. Other image is of Steam In Home Streaming latency showing low numbers

https://photos.app.goo.gl/TcelJLb4N4qzLMaR2

**Comment by jimmiemaul** [comment]
Issue resolved. Windows 10 Game Bar was enabled, the DVR feature was causing lags and stutters. Have reported this to @Codeusa who has disabled this by default in the next patch. Stutters gone, no further changes required.
