### ISSUE TITLE
Desktop freeze through chromebook.

### ISSUE THREAD

**Issue by brimaster2000** [RainwayApp/bug-tracker#150]
My rainway just freezes after a a second on my desktop when I connect with a white screen on the top left corner where my game is loading, and then when I retry its stuck on starting game until I reload the website. I originally thought it was a nvidia problem but it isn't. I'm running off a chromebook. Sometimes I get lucky and my game opens and I can see the title screen. It does this at home and school.

**Comment by Jessomadic** [comment]
This should be fixed with the Octane update. (Newest big update) Try again and if it works better close the issue. If it does not keep it open and send logs

**Comment by brimaster2000** [comment]
This issue had been fixed via the update.
