### ISSUE TITLE
Error when loading UI

### ISSUE THREAD

**Issue by JohnsonJPJ** [RainwayApp/bug-tracker#152]
I get this everytime my computer restarts. 
https://i.gyazo.com/a0e6d75271a0cccffd3fbfb6a0a2f57f.png

**Comment by neseih** [comment]
It seems like 2.0.1 doesn't include all files. Try installing version 2.0.0 and update to 2.0.1 afterwards.

**Comment by JohnsonJPJ** [comment]
That fixed it for me.
