### ISSUE TITLE
Stuck on Registering DNS

### ISSUE THREAD

**Issue by Lazermn03** [RainwayApp/bug-tracker#16]
When doing the first time set up, it gets stick on registering DNS. I have reinstalled the app, rebooted, and flushed the cache many times. I also have tried on all the versions of the server app releases today with the same issue.

**Comment by Lazermn03** [comment]
Screenshot of screen it's been stuck on all day.

https://1drv.ms/i/s!At6vTy_UY3BTg-cu8qRxOcpmCEj0WA

**Comment by Simfukwe** [comment]
![registering dns entries](https://user-images.githubusercontent.com/35647377/35190698-6cc649fc-fe35-11e7-8dd3-2da144409a24.PNG)
Yeah same here. I've already deleted cache, uninstalled and reinstalled, updated to latest version, etc. HELP!

**Comment by Shadsterwolf** [comment]
I had the same issue,

I have a Comcast Modem rental (which has both lan/wifi) with a wireless netgear router.
I had my rig connected directly to the modem (which I thought shouldn't cause issues since I have all firewall things off)

I fixed this by just plugging my rig into the router, instead of directly to the modem.

**Comment by raptaml** [comment]
That does not fix it for me. I am behind a  router since launch and have been stuck with "registering dns" ever since... Made a different account, patched rainway to latest, several host shutdowns

**Comment by Shadsterwolf** [comment]
I definitely recommend then to tweak some of the settings in the router.
Check for pre-built firewall and security junk on it. As well as possible firmware updates.
I strongly believe it's a modem/router kind of problem.

**Comment by klukule** [comment]
Here is the error I get (when I get stuck in "Registering DNS Entries")
![image](https://user-images.githubusercontent.com/3607341/35193558-9f3b8b44-fea4-11e7-8aec-f62547cb359a.png)

**Comment by klukule** [comment]
well there must be something else, since this error means in REST "Unprocessable Entity" which means that server just doesn't like the data I sent him (which is probably because of the LocalIP and MacAddress being null)

**Comment by klukule** [comment]
OK, Update.... that worked... which means it's problem when you have more than one NIC (I have 8 ports in my server) :D

**Comment by raptaml** [comment]
Confirmed. Disabling additional interfaces does the trick. Rainway should auto-choose the primary one via gateway check or something

**Comment by klukule** [comment]
That would be hard.... since some people can have multiple NICs connected to multiple sub-networks and multiple WANs... so easiest thing would be to enumerate NICs and let user choose

**Comment by healingbrew** [comment]
Should be resolved now.
