### ISSUE TITLE
After newest update can't even use Rainway Locally anymore

### ISSUE THREAD

**Issue by Jessomadic** [RainwayApp/bug-tracker#162]
![image](https://user-images.githubusercontent.com/35648348/35816518-e9f7d514-0a68-11e8-9896-7ec8f51f7b47.png)
Yesterday I was able to use Rainway locally. There was an update overnight that i downloaded when I woke up. After that I was no longer able to use Rainway. This comes up both local and non

**Comment by Jessomadic** [comment]
![image](https://user-images.githubusercontent.com/35648348/35816615-220fbe3a-0a69-11e8-8f3e-dda4c1fe0fa0.png)

**Comment by Codeusa** [comment]
We did not make any changes to Rainway that would change our networking. You should be looking at your network or try resetting Rainway.

**Comment by Jessomadic** [comment]
@Codeusa Yeah it is most likely my network. As I have told you many times at this point (sorry). Do you see anything in those settings that I should change or do they look ok?

**Comment by Jessomadic** [comment]
I have fixed both this and remote streaming (most of the time) by using AirVpn to allow me to port forward. As well as turning off Ipv6 and DDNS

**Comment by Jessomadic** [comment]
I have it working perfectly now without having to use a VPN. Thanks to Andrew coming in and fixing it. from a latency side it is still unplayable but much better. MAKE SURE YOU TURN ON HARDWARE ACCELERATION!
