### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by bananyog** [RainwayApp/bug-tracker#169]
After using Rainway multiple times in one session (not closing Rainway) Rainway for some reason keeps all the memory it's stored and is taking up gigabytes of ram over a period of time. I have 16GB of ram and at times it's using 9GB at a time causing severe lag in some games that are trying to use ram.

(Do not have a photo of it at the moment, but will add one when I can)

**Comment by roman380** [comment]
We have some memory leaks (esp. related to NVIDIA GPUs) fixed, the fixes are expected to appear in next released version.

**Comment by BetaLeaf** [comment]
Just an FYI, the latest update should've fixed this, so make sure you update and report back @bananyog.

**Comment by yu42hit** [comment]
i believe it still hasn't been fully patched. I'm getting severe freezing with Destiny 2.

**Comment by roman380** [comment]
@yu42hit do you see memory leakage along with the freezing?

**Comment by yu42hit** [comment]
i checked again, and it appears that's not the case, sorry. thought it was. I still have an open issue about it though: https://github.com/RainwayApp/bug-tracker/issues/157

**Comment by Jessomadic** [comment]
@bananyog This was patched two updates ago. Is it still doing it? If not your should close the issue

**Comment by bananyog** [comment]
Sorry, had no access to a PC for a bit, memory leak error on my end seems to be gone. Good work on fixing the bug, This is now closed
