### ISSUE TITLE
Rainway automatically starts

### ISSUE THREAD

**Issue by Legend-Rider** [RainwayApp/bug-tracker#172]
I would like it if there was an option to disable auto start for Rainway.

**Comment by Jessomadic** [comment]
Right click on the mini icon in taskbar and uncheck start on boot
![image](https://user-images.githubusercontent.com/35648348/36167825-38ca20a4-10c5-11e8-9663-a32a6d3205f0.png)

**Comment by Jessomadic** [comment]
Please close this Issue after you do it

**Comment by Legend-Rider** [comment]
Thank you!  I checked the list and some how missed that XP
