### ISSUE TITLE
Rainway Server not launching, starting from version 0.2.26.0

### ISSUE THREAD

**Issue by Policegking** [RainwayApp/bug-tracker#175]
I've just updated my rainway server on my main rig, and now it won't launch anymore. 
I tried restarting my PC.
Uninstalling Rainway.
Reinstalling Rainway.
Rebooting the PC again.
Result is alwas: It doesn't open, no error or anything.

My Hardware-Info:
[DxDiag.txt](https://github.com/RainwayApp/bug-tracker/files/1734200/DxDiag.txt)

**Comment by Codeusa** [comment]
A patch has been pushed that should address this. @Policegking let me know if it solves your issue. (0.2.27)

**Comment by Policegking** [comment]
I've updated but the issue persists, I then did a fresh install and still the same result (I then tested reinstalling with my antivirus protections deactivated, but nothing changed (just to make sure)). 

Is there anything I could provide to you, to help resolve this issue?

**Comment by Codeusa** [comment]
Sure, provide me your Radar.log and Server.log located in your cache folder.

**Comment by Policegking** [comment]
Those are the files I found in the RainwayInc-Folder in my user-directory. 
But they didn't seem to update when I tested rainway yesterday.

According to Windows Explorer: Radar.log and Server.log were both last changed on february second.


[Radar.log](https://github.com/RainwayApp/bug-tracker/files/1734674/Radar.log)
[Server.log](https://github.com/RainwayApp/bug-tracker/files/1734673/Server.log)

**Comment by Codeusa** [comment]
@Policegking does this happen with the latest version

**Comment by Policegking** [comment]
Yes, no changes so far. 

I don't know if this is related, but it's exactly the same situation when I try to run any kind of java swing Application (haven't tried JavaFX so far) since the fall creator's update (No App will open, and no error message). 
I'm not sure if this is in any way related because rainway still worked when the java issue already occured.

**Comment by Policegking** [comment]
I started my PC today and suddenly after about 10 Minutes after booting, rainway started itself automatically. I could login and everything was fine, no problems. 
To test if everything works again I activated the start of rainway at boot time (just in case it maybe only starts that way) and then closed the Application. 
Trying to open it again resulted in the same situation as always no reaction at all.
Rebooting the System didn't bring up the rainway application either.

I hope this additional info might help regarding this issue.

(I'll comment if it starts again randomly by itself or if I find anything else that might be helpful)

**Comment by Codeusa** [comment]
Can you start rainway from the "Start Rainway" option i nthe start menu? 

When you do that is Radar running as a service or do you see "ServiceManager" or "Radar" or "Rainway" in the task manager?

**Comment by Policegking** [comment]
None of those are running in the Task-Manager, but I tried looking RainwayRadar under "Services" and found it. 
It was halted and the moment I started it through the Services-Tab in the Task-Manager, Rainway booted up just like normal.

I then closed everything again and tried starting Rainway again while RainwayRadar was stopped and it's not starting like before, but starting the RainwayRadar Service immediately brings up the Rainway Application.

**Comment by Codeusa** [comment]
Go to C:/User/YourUserName/RainwayInc/ServiceManager and give me the ServerManager.log

**Comment by Policegking** [comment]
I would love to give you the ServiceManager.log but the file is empty, the file was changed last on january 31 2018

**Comment by Codeusa** [comment]
@healingbrew service manager seems to be failing to start the service, needs more investigation and possible fix. Likely not just hurting this user.

**Comment by healingbrew** [comment]
Was the state "Stopped", "Halted", "Paused", or "Starting up?"

**Comment by Policegking** [comment]
The state was "Stopped"

**Comment by Codeusa** [comment]
Try the latest update and see if this is resolved

**Comment by Policegking** [comment]
I installed the latest update and rebooted my pc. But Rainway still won't boot unless I manually start the RainwayRadar Service

**Comment by healingbrew** [comment]
Does a window show up at all?

**Comment by Policegking** [comment]
Only the UAC prompt by Windows, but after that nothing.

**Comment by Policegking** [comment]
Just updated to the newest version of Rainway (Octane 1.5) today and it seems to have fixed the issue, now Rainway starts without issue. 

(Even terminated the RainwayRader service to see if it would automatically start up again when I start Rainway, and yes it does and works fine)

Thanks for all the help from you people, just tell me when I should close the issue or just do it yourself, it's settled for me and maybe for @gsxryan as well?!
