### ISSUE TITLE
Request: itch & Twitch support

### ISSUE THREAD

**Issue by azumukupoe** [RainwayApp/bug-tracker#177]
Game scanner for itch & Twitch?

**Comment by Jessomadic** [comment]
Just add them as nonsteam games. Also you might want to fix the spelling of the issue

**Comment by healingbrew** [comment]
Does itch.io have a launcher?

**Comment by azumukupoe** [comment]
GameSessions?

**Comment by healingbrew** [comment]
What?

**Comment by healingbrew** [comment]
Closing this in favor of a dedicated thread #192
