### ISSUE TITLE
Game Analyzers

### ISSUE THREAD

**Issue by neptuwunium** [RainwayApp/bug-tracker#192]
The following is a list of platforms that are (pending to be) implemented.

- [x] Twitch/Curse
- [x] Epic Games
- [x] Nexon
- [x] UWP (rewrite)
- [ ] Itch.io (needs metadata)
- [ ] GameSessions (investigating)
- [ ] NCSoft (investigating)
- [ ] Rockstar (investigating)
- [ ] placeholder

Please reply with any issues or additional analyzers

**Comment by Jessomadic** [comment]
Can you add Rockstar Launcher to the list as well?

**Comment by healingbrew** [comment]
sure thing.
