### ISSUE TITLE
Add support to open Steam/Battlenet/Origin/ETC

### ISSUE THREAD

**Issue by Jessomadic** [RainwayApp/bug-tracker#193]
Allow the Client to run closed steam and the such. so that you don't have to start  a desktop session then have to close it THEN run the game

**Comment by Codeusa** [comment]
This makes the most sense, we want to limit arbitrary remote access time @healingbrew so lets just launch the platforms if they're missing.

**Comment by Jessomadic** [comment]
@codeusa that makes sense

**Comment by BetaLeaf** [comment]
While you are at it, can we get the same for Remote Desktop?

**Comment by Jessomadic** [comment]
@betaleaf I am still using yours and it works fine. Thanks for that btw :)

**Comment by BetaLeaf** [comment]
No problem. Rainway team is more than welcome to distribute it and use it as they want. If you want a version that hides the tray icon, let me know. 

Just add ```Opt("TrayIconHide",1)``` to the top of the source code, then recompile. https://www.autoitscript.com/autoit3/docs/intro/compiler.htm

**Comment by Codeusa** [comment]
This will be added in the next update by default
