### ISSUE TITLE
Steam Games not showing up

### ISSUE THREAD

**Issue by Praxis459** [RainwayApp/bug-tracker#197]
I have rainway installed and it was working well until this morning.  Went to go get a list of my games this morning and none of my non shortcut stream games would show up.  Other games from Origin and Uplay and Blizzard showed up fine.  In my log files BetaLeaf came across this line.
`2018-02-28 08:15:42,471 [71] WARN Rainway.Core.Network.Http.RainwayApi - Failed to fetch game list
`
Windows 10 Version 1709
Rainway server version 0.2.46.0
Most current Nvidia driver.

**Comment by BetaLeaf** [comment]
Hope someone will be able to help you. I'll be watching the thread.

**Comment by Praxis459** [comment]
Attaching log file after update that was just pushed out.

[Server.log](https://github.com/RainwayApp/bug-tracker/files/1770212/Server.log)

**Comment by Praxis459** [comment]
Here is an updated service log with debugging enabled.
After the platform:Steam lists all the acin's for my games I do notice this entry:
`2018-03-01 07:12:18,041 [41] WARN Rainway.Core.Network.Http.RainwayApi - Failed to fetch game list; got Null response`
[Server.log](https://github.com/RainwayApp/bug-tracker/files/1771250/Server.log)

**Comment by Praxis459** [comment]
My steam games are now showing up correctly Thank you for your help you can close this ticket.
