### ISSUE TITLE
Rainway Self-Host?

### ISSUE THREAD

**Issue by BetaLeaf** [RainwayApp/bug-tracker#199]
I would love the ability to self-host everything I need to use Rainway. So for example, instead of going to play.rainway.io to play my games, I can just use my ip address or domain name. This would give a number of benefits.

  * A proxy for workplaces that block the play.rainway.io domain.
  * A long-term future-proof plan for when rainway eventually retires. (Hope that never happens though)
  * Reduce resource usage for the Rainway API on Rainway Official servers.
  * Privacy. 
  * Redundancy for a server maintenance.

**Comment by Jessomadic** [comment]
I was just thinking about this today and was going to post it. This would be a better way/a way for some people I be able to use rainway at all. Most schools and workplaces won’t go out of their way to block a up but something like play.rainway.io is going to be picked up by their filters is seconds. If possible I would like to see this have a shot.

**Comment by Codeusa** [comment]
We tried this with Ulterius, it does not scale and at this time have no plans to build any of this functionality in.

**Comment by BetaLeaf** [comment]
</3

**Comment by BetaLeaf** [comment]
For me pesonally, its mostly to make sure that when Rainway eventually closes its servers, I can still continue to use Rainway self-hosted.

**Comment by Codeusa** [comment]
If we ever shut our doors and our technology wasn't bought out, we will ensure users can self-host.

**Comment by BetaLeaf** [comment]
Good to hear.

**Comment by BetaLeaf** [comment]
@Codeusa any new plans to implement the core rainway functionality to self host?

**Comment by TheMulti0** [comment]
I love the idea. It can be a custom version (perhaps even one that you have to build yourself) that will have the self hosted client and all as well as more customization of network behavior and such.
