### ISSUE TITLE
Debug mode - server won't start.

### ISSUE THREAD

**Issue by TristisOris** [RainwayApp/bug-tracker#216]
#reproduce:

activate Debug mode in tray 
got message "Rainway will now restart."

after that app closing forever. i can't run in manualy.
v.0.2.54

**Comment by TristisOris** [comment]
i reinstalled rainway. problem is not gone.
where settings store?

**Comment by TristisOris** [comment]
solved.
server don't work when & **after** RDP session. what's the problem?

1. turn on PC remotely 2. turn on rainway via RDP 3. got nothing.

**Comment by Codeusa** [comment]
@healingbrew can you look into a work around for this

**Comment by healingbrew** [comment]
duplicate of #9
