### ISSUE TITLE
Display is locked to off-monitor, cant switch between displays through web client.

### ISSUE THREAD

**Issue by danteteresi** [RainwayApp/bug-tracker#225]
Rainway locked on to my monitor that was off and wouldn't let me switch it to the display that was on, as it would go back to the one that was off after a few seconds.

**Comment by BetaLeaf** [comment]
Try hitting Win+P and set it to the intended monitor. If you can't see the menu, press it twice and give it a sec to switch monitor mode. You may need to repeat this until its set correctly.

**Comment by danteteresi** [comment]
Currently issue is fixed, cant redo the issue anymore to try it out. :( guess is should close this?

**Comment by BetaLeaf** [comment]
Ah ok. Glad the issue is fixed. Yea, go ahead and close the issue.

**Comment by danteteresi** [comment]
Thanks for responding :>
