### ISSUE TITLE
panel.pond not found!?

### ISSUE THREAD

**Issue by KrisPCream** [RainwayApp/bug-tracker#23]
everytime i try to launch the app it does nothing for about 3 or 4 mins. Then a little error pop up comes up saying it can find a thing and keeps popping up over and over.

![image](https://user-images.githubusercontent.com/31629049/35190880-835b7b06-fe21-11e7-89e6-71b861fd8d7e.png)

it wont launch rainway and just keeps saying that

**Comment by Zenexer** [comment]
Uninstall Rainway, download a fresh copy, and reinstall it.  This looks like a bug that might've been fixed.  You're receiving the error because Rainway is trying to access `%UserProfile%` from a process running under the `SYSTEM` account.

**Comment by Codeusa** [comment]
This was resolved in the latest update, this was caused by users being flagged by cloudfront.

**Comment by origamiwhale** [comment]
Hey @Zenexer, sadly I'm experiencing the same issue on Rainway build 0.1.5
My error message looks exactly like the @KrisPCream 's.

Tried uninstalling and reinstalling, as well as `Checking for updates`.

If you need any other debug info I'll be happy to provide it.

Cheers,

**Comment by Codeusa** [comment]
@origamiwhale go to 

C:\Windows\System32\config\systemprofile\AppData\Roaming\RainwayInc\Radar

And provide me the Radar.log file

**Comment by origamiwhale** [comment]
Here it is
https://pastebin.com/9B9gyRFJ

cheers,

**Comment by origamiwhale** [comment]
@healingbrew , @Codeusa just letting you guys know that on latest build (0.1.13) this issue doesn't occur any longer on my machine 👌🏻

**Comment by healingbrew** [comment]
Issue has returned apparently.

**Comment by Codeusa** [comment]
This is caused by anti-virus blocking our CDN. Because its the same place our installer is hosted and they think its a virus.

**Comment by healingbrew** [comment]
🤔

**Comment by March-happy** [comment]
Still appear. I wonder where's the panel.pond because some CDN services like AWS is quite slow and may be blocked in Mainland China.
