### ISSUE TITLE
Rainway keep restarting

### ISSUE THREAD

**Issue by XCanG** [RainwayApp/bug-tracker#233]
**Bug ID: 82a723b9-0f74-4dd6-ae4d-7817f8478a24
Steps to reproduce the problem:**
Start rainway on server side, logout and login (probably in another account, but may be same too. Then open play.rainway.io and login, after game list received on server side rainway crashed. It happen only after relogin process was passed.

**What is the expected behavior?**
Not to crash server when open website.

**What went wrong?**
Restarting rainway when game list shown to client

**Did this work before?**
It work normally when I not touch relogin on server side, after I relogin this problem started.

**Does this work in other browsers?**
Probably not browser-related

**OS Info:** Windows 10 Professional x64 [10.0.17134]

**Rainway Server Version:** 0.2.66.0

**Rainway Frontend Version:** 1.0.23.0

**Comment by Codeusa** [comment]
Temporary work around @XCanG is to go to (C:\Users\yourusername) open RainwayInc and delete the Server folder, make sure Rainway is closed at this point. Restart Rainway and it should work.

**Comment by XCanG** [comment]
@Codeusa hm, it still not work, I'm resetting settings, but it still keep crashing rainway
may be sevveral bugs are sended, I at least copy that Bug ID: b3084472-fdac-4d09-a9c8-2eaa90ed3eb7

**Comment by XCanG** [comment]
May be with newer version 0.3.0 this bug was fixed. Right now I don't see this issue (or can't reproduce).

**Comment by Codeusa** [comment]
It was. Sorry for the delay in responding, let me know if you need anything else.
