### ISSUE TITLE
Monitor changes since last setup

### ISSUE THREAD

**Issue by bramnet** [RainwayApp/bug-tracker#237]
It would be nice if we could change the monitor and sound setup either from the client or if the server would move to the next alternative if sound devices and monitors have changed since the first time setup.

**Comment by Codeusa** [comment]
You can change them from the client and the server. 

![image](https://user-images.githubusercontent.com/1297077/41206791-fd429f7e-6cd7-11e8-842f-3dad80d47bc3.png)

**Comment by bramnet** [comment]
Whoops. Either it was added with .3 or I somehow didn’t notice.
