### ISSUE TITLE
Rainway 60 FPS setting bug

### ISSUE THREAD

**Issue by yu42hit** [RainwayApp/bug-tracker#248]
Found the weirdest bug with Andrew today. Apparently when i set the FPS to 60 in the dashboard the latency goes up big time. If its any other FPS it works fine (Or at least any higher fps). Im using a Macbook pro 2015 15" with dedicated graphics for my client. My host has a 1060 6g, i5 Skylake, and a 60ghz monitor. If I missed anything feel free to respond.

**Comment by roman380** [comment]
Any specific game to reproduce the latency or with 60 it shows up just with anything?

**Comment by yu42hit** [comment]
@roman380 I've tried No Man's Sky with the 120 fps option and it works very well, but with 60 fps in any game, its bad.

**Comment by yu42hit** [comment]
Bug has been fixed.
