### ISSUE TITLE
Failed to configure certificates

### ISSUE THREAD

**Issue by qwertimus** [RainwayApp/bug-tracker#26]
Upon start-up, the program gets stuck attempting to configure certificates.
I've tried deleting the cache, reinstalling Rainway, and rebooting the computer.

Windows 10 Fall Creators update / Rainway 0.1.4

![certificates](https://user-images.githubusercontent.com/1412513/35190941-231dd76a-fec2-11e7-80f5-c5fd0339a5c8.PNG)

**Comment by Zenexer** [comment]
Wait a minute or two and click Retry.

**Comment by qwertimus** [comment]
Yeah, I've been trying on-and-off since it first launched, always that error.

**Comment by jimmeldrum** [comment]
sometimes my client successfully configures the certificates but mostly it fails with this error
