### ISSUE TITLE
Location `systemprofile\Desktop` is not available

### ISSUE THREAD

**Issue by Migushthe2nd** [RainwayApp/bug-tracker#267]
# Location is not available
## Steps

- Open Rainway
- Open Settings
- Click account
- Click 'Upload Avatar'

## What happens

The explorer window does open, but is seems to default to `C:\WINDOWS\system32\config\systemprofile\Desktop`
The image is in Dutch
![image](https://user-images.githubusercontent.com/22274715/52062757-6951a000-2571-11e9-9150-4bd8e5526a37.png)
You can click ok OK, but if you try to select one of the libraries, the error pops up again:
![image](https://user-images.githubusercontent.com/22274715/52063088-25ab6600-2572-11e9-8885-5841aa62f099.png)

## What is expected

Default to normal user's desktop folder. It shouldn't try to open the systemprofile's desktop folder.

## Host

 - OS: Windows 10 Pro
 - Version: 1.0.0.0

**Comment by TheMulti0** [comment]
Same for me.

**Comment by JTTM** [comment]
Thanks for the report. This is already known and being fixed.

Also, it would be best to report issues on the Discord right now. Thanks.

https://rain.gg/discord

**Comment by knagieknagger** [comment]
Still applicable to 1.0.7.0
The error only changes the name to show the selected library, attached the English version of the error message.
![error](https://user-images.githubusercontent.com/7049201/54073134-ef08ef80-4283-11e9-8c40-4f2a29e3c439.png)

**Comment by Amphyross** [comment]
Just ran into this issue
was checking if this was related to issue #295

however it also happens when light theme is applied
![image](https://user-images.githubusercontent.com/47581522/54433781-aa091100-46fa-11e9-9d61-ca9555ad68d8.png)

Windows 10 Pro 1809
OS build 17763.316

**Comment by healingbrew** [comment]
Should be fixed in the next update.
