### ISSUE TITLE
"Steam is not runnning" error althouth Steam is runnning on host. And black screen

### ISSUE THREAD

**Issue by Hiragi1585** [RainwayApp/bug-tracker#27]
please follow title.

When I press the button on the Desktop session, the session is started but only the black screen is displayed.
What I can only to see is overlay screen. 

OS:Windows10 version 1709
Rainway version 0.1.4
Browser: Firerfox and Chrome
Chrome has no extension.
Firefox has some extensions but disable all.

(This report was translated using Google translation.)

**Comment by Jessomadic** [comment]
This has been fixed update Rainway

**Comment by Codeusa** [comment]
Fixed in 0.1.6, comment if its not.
