### ISSUE TITLE
Scroll wheel doesn't work on the Dashboard

### ISSUE THREAD

**Issue by ImJezze** [RainwayApp/bug-tracker#274]
# No scroll-bar in Games tab

## Steps

- Open the Rainway
- Select Games tab

## What happens

Rainway has detected over 100 games, but there is no scroll-bar to get to the bottom of the list. The mouse-wheel doesn't work either.

## What is expected

A scroll-bar to scroll down the list by dragging the bar or using the mouse-wheel.

**Comment by lynn** [comment]
Thanks for reporting this.

Scrolling your games list with the mouse wheel _should_ work if you click the space between the game cards first, to focus the window. I added a subtle scroll bar anyway, to make this more obvious.

If you connect to https://play.rainway.com in your browser, do you experience the same behavior, or are your games scrollable there?

**Comment by ImJezze** [comment]
Sorry for my late response. I updated to 1.0.6.0 and the games tab now has a scollbar. Thanks for that!

However the mouse wheel still does not work in the desktop client (games tab, settings tab). I clicked between the game tiles as you suggested, but no luck. I also connected to the web version and there the mouse wheel works just fine.

**Comment by lynn** [comment]
Hey there, glad there's at least one way you can scroll your games now :) But still, the scroll wheel should really work. We'd like some more info from you so we can solve this issue.

* Can you tell us what version of Windows you have installed, and if there's anything you can think of that might be interfering with the scrolling?
* Maybe silly, but -- what mouse are you using?
* Does scrolling work on the Settings tab?
* Have you had similar issues in other apps before?

**Comment by ImJezze** [comment]
I'm using Windows 10 Version 1803.
The mouse is a Logitech MX Anywhere.
The scrolling is also not working on the Settings tab.
I never had any similar issues in other apps before.

However, I tested the problem on another PC with a similar configuration and the scrolling worked properly. Therefore I think this issue can be closed. If I find out what the problem is on the original PC, I'll leave a comment.

Thanks for your support!
