### ISSUE TITLE
Unable to remove Steam account

### ISSUE THREAD

**Issue by Amphyross** [RainwayApp/bug-tracker#279]
# Title

Unable to remove Steam account both in-browser and the desktop client

## Steps

- Go to account settings
- Click the remove button on Steam's icon
- "Connected" text will very briefly change to "Pending..." before reverting back to "Connected"

## What happens

Upon trying to remove steam from the account, "Connected" text will very briefly change to "Pending..." before reverting back to "Connected", thus not removing the account from Rainway

![ayesskmtn7](https://user-images.githubusercontent.com/47581522/53277353-19c24800-36c9-11e9-8e77-2bbcf1794a2e.gif)

## What is expected

Steam should change to "Not Connected" and remove the connection to Rainway

![image](https://user-images.githubusercontent.com/47581522/53277410-52622180-36c9-11e9-8c19-74e41632074e.png)

## Host

 - OS: Windows 10 Pro
 - Version: 1809
 
## Browser

 - OS: Windows 10
 - Version: 1809 / 17763.316
 - Browser: Brave
 - Browser Version 0.60.45 Chromium: 72.0.3626.109

**Comment by agentd00nut** [comment]
Steam account details were being removed but were not properly being seen as removed when checking a users integration status.

Basically it actually worked but wasn't properly updating the frontend.

This should no longer be an issue.
