### ISSUE TITLE
Black Screen when running game

### ISSUE THREAD

**Issue by Jessomadic** [RainwayApp/bug-tracker#28]
When running the newest version of the Rainway Server (0.1.4) on a Windows 10 based system and going to a new computer also on the newest version of Windows 10 I get a black screen whenever I try to run a game. I walk downstairs to my host computer and the game has started to run like it should on my host computer. This issue happens on both Chrome and Firefox (i5-7600k 5.1Ghz 16GB ram 2400Mhz 1060 6Gb 2000Mhz)

**Comment by notdisliked** [comment]
Seems like a duplicate of #19, might post your specs in that thread and close this one for cleanliness.
