### ISSUE TITLE
Client Machine Connecting Loop/Stuck

### ISSUE THREAD

**Issue by RossDanbyGamer** [RainwayApp/bug-tracker#282]
When connecting to my gaming pc locally, I log in on the page play.rainway.com and then the page says connecting, it has stayed on the page since and rebooting both server and client doesn't change. I have attempted to fix this issue with the support channel, they are just as confused as me.

**Comment by apecoraro** [comment]
Are you still having this issue?

**Comment by RossDanbyGamer** [comment]
Hi There! I'm happy to report that the problem has been solved! 👍
