### ISSUE TITLE
Rainway installs, but fails to launch

### ISSUE THREAD

**Issue by portalpiggy** [RainwayApp/bug-tracker#284]
## Title
Installer finishes, but when the application is launched, nothing happens (Ver 1.0.6)

## Did it work/not work on a previous verison

It worked on the beta version up untill the full release

## Steps

Download the installer from the Rainway site
Run the installer
Open application from desktop

## What happens

Installer runs correctly, asks for admin permission and then closes, but when the icon is selcted from the desktop, nothing launches

## What is expected

Application should run and open the Rainway control panel

## Host

 - OS: Windows 10 Pro
 - Version: 1803
 
## Browser

N/A

## Logs
[SquirrelSetup.log](https://github.com/RainwayApp/bug-tracker/files/2917705/SquirrelSetup.log)
There is no Server.log

**Comment by sakshamgoyal01** [comment]
if only this was stackoverflow.....
*MARKED AS DUPLICATE*
i already opened this issue and so have many others.

**Comment by portalpiggy** [comment]
whoops
