### ISSUE TITLE
Unable to Link steam account. (plus a weird chrome window)

### ISSUE THREAD

**Issue by Blakeinstein** [RainwayApp/bug-tracker#285]
# Steam Link doesnt work

logging in to steam and accepting link returns false page that (https://rainway.com/oauth/?success=false&service=steam&error_code=0&error_message=user-not-logged-in) that says link successful.

## Steps

- Open Rainway
- Go to Settings
- Go to Accounts and scroll down.
- Click on steam, in the succeeding window log in in to your steam account and then confirm the integration.
- Resulting page would have a url stating the op was a failure with the error user not logged in but the page would say integration successful.
Workaround:-
- Login on the page play.rainway.com in a browser.
- Click on steam in rainway,settings,accounts
- Copy the URL of the web page and open in the same browser you logged in to in the first step.
- Now log in and confirm integration.
- The link would successfully form.

## What happens

Failure to form a link, with a message saying it was successful, and the confirmation page should opens in a new browser (which looks like chrome launched in safe mode w/o cookies and plugins)

## What is expected

Successfully form a link through the app, and the confirmation page should open in the default browser.

## Host

 - OS: Windows 10 Home Single Language
 - Version: 1809
 - Build:  17763.316
 
## Browser

 - OS: Windows 10
 - Version: 1809
 - Browser: Chrome
 - Browser Version: 72.0.3626.119

**Comment by agentd00nut** [comment]
Needing to use the browser you are logged in on is a known issue.

The `success=false` not showing an error has been fixed, which should remove some of the confusion.
