### ISSUE TITLE
[UI Enhancement] Friends Server Offline

### ISSUE THREAD

**Issue by JTTM** [RainwayApp/bug-tracker#288]
I think it would be beneficial if the "Friends Server Offline" error is changed to something like "Friends is still in development" until the friends server is available.

There have been quite a few people asking on the Discord about the error despite the multiple announcements made in the past.

**Comment by lynn** [comment]
Fixed — the add friends button is marked “Coming Soon!” now.

Sorry for the mixed messaging on our end. We intended to have the Friends Server online a few days after the 1.0 release, but it ended up being kind of a rabbit hole to get fully working, and we didn't want to prioritize it right now. It'll make more sense in the future when we move focus to features like Rainway Party.
