### ISSUE TITLE
Open dialogue not supporting File Manage dark mode/theme

### ISSUE THREAD

**Issue by Knagie** [RainwayApp/bug-tracker#295]
Open dialogue not supporting File Manage dark mode/theme

I haven't tried it in a previous version so I don't know if it is, I would think it is.

## Steps

- Open the dialogue to change your avatar
- Look at the way the window is displayed with dark and light theme mixed or one specific one.
- Close the dialogue and re-open it.
- Look at the way the window is displayed with dark and light theme mixed or one specific one.
- Repeat

## What happens

When you open the file manager dialogue for selecting an avatar the windows file manager the window changes between light and dark theme of the file manager each time you open the dialogue.
It doesn't have one specific way of showing up, see the attached screenshots.
![image](https://user-images.githubusercontent.com/7049201/54073349-79525300-4286-11e9-8869-969012ccc044.png)
![image](https://user-images.githubusercontent.com/7049201/54073356-81aa8e00-4286-11e9-9d22-aaa458174fd9.png)
Sometimes it shows up correctly:
![image](https://user-images.githubusercontent.com/7049201/54073353-7e170700-4286-11e9-80fd-40a8ab3a5a36.png)

## What is expected

That it would be in the chosen theme of the Windows instalation/user specific theme.
Looking like this:
![image](https://user-images.githubusercontent.com/7049201/54073353-7e170700-4286-11e9-80fd-40a8ab3a5a36.png)
## Host

 - OS: Windows 10 Pro
 - Version: 1809

**Comment by healingbrew** [comment]
Should be fixed in the next update.
