### ISSUE TITLE
Unable to move steam account to new rainway account

### ISSUE THREAD

**Issue by Amphyross** [RainwayApp/bug-tracker#296]
# Title

After removing Steam from old Rainway account, new Rainway account says there was an error adding the Steam account

(I am using client, as there seems to be an update that I cannot test with the pc's local browser anymore
and I do not have a separate device available at the time of writing)

## Steps
(will be using account 1 and account 2 for easier following
account 1 = old rainway account
account 2 = new rainway account)

- Have a steam account linked on account 1
- Remove steam account from account 1
- Try to add steam account to account 2
- Account 2 will result in an error
- Go back to account 1 and steam will be stuck in "pending..."
- (update after finishing typing this issue)
- Account 2 is also stuck on "pending..."

![7mppKF7cFJ](https://user-images.githubusercontent.com/47581522/54075302-5ebab280-4263-11e9-8767-e59f89171d75.gif)

## What happens

Steam account appears to not be removed fully from the old Rainway account,
and is unable to be linked to the new Rainway account after being removed from the old account

## What is expected

Steam account should become linked to second (new) account after being unlinked from the first (old) account

## Host

 - OS: Windows 10 Pro
 - Version: 1809 (OS Build 17763.316)
 
## Browser

(there seems to be an update that we cannot use the browser on the local device
and I am unable to test with a different browser/device at the time of writing)

**Comment by Amphyross** [comment]
Also apologies, I am unable to provide a screenshot of the error message now that both are stuck on pending

It was the usual "Message the support chat, or submit a new issue" text

**Comment by Amphyross** [comment]
I checked again today, it said "not connected" so I attempted to add it again
This was the error message I received when using the new Rainway account

![image](https://user-images.githubusercontent.com/47581522/54090600-e1b33a00-4343-11e9-993f-28facdb8ac90.png)

Both accounts now appear as "Not Connected"

**Comment by agentd00nut** [comment]
Give this a go again, There were a few issues with the api response..

Some notes;
1. There's nothing limiting the steam account from being linked to two rainway accounts.
2. The revoking process and sign up processes should be working fine.

There is a bit of delay and buggyness with the state of the integration buttons.  For example when revoking steam it seems to not do anything on the first click and then clicking a second time seems to work.  I can confirm that on the first click it **does** properly revoke the account and it's just a problem with communication between the front end and backend.

We have some ideas in place to improve the communication between the gui's and the api to keep things in better sync that should be implemented relatively soon.

For now if you feel the state of the integration buttons aren't matching the actions you've taken, leave the settings by going back to your game menu or the news menu and then go back to settings.  This should force the GUI to reach back out to the api to get the current state of things.


If you still have trouble please reach out to agentd00nut within the rainway discord.
