### ISSUE TITLE
[Bug] Stream error - Error encounted in stream engine: Bad encoding config

### ISSUE THREAD

**Issue by pianoboy8** [RainwayApp/bug-tracker#30]
I attempted to run a game from my steam account on the web client (attempted both on my chromebook and on the server laptop), and it shows this error message:
"Error encountered in stream engine:
Bad encoding config"

I personally attempted to run Undertale & The Binding of Isaac Rebirth +DLC, and in both games, the web client gives this error.

Now while the web client doesn't show the game, the server itself opens the game up like it would if I was playing without rainway.

I'm currently using v0.1.4 of rainway, my chrome browser is 63.0.3239.132 (laptop) and 63.0.3239.140 (chromebook).
Laptop is an inspiron 15 5567 with a Radeon R7 m445 graphics card and an Intel HD Graphics 620.
I'm using Windows 10 1709, Build number:16299.192.
Chrome extensions currently enabled are:
Application Launcher for Drive
Chrome Remote Desktop
Crosh Window
Docs
Google Docs Offline
Google Keep Chrome Extension
Heidi's Infinite Sudoku
Lightshot (screenshot tool)
McAfee Web Advisor
Reddit Enhancement Suite
uBlock Origin

Current Server.log:

> 
> 2018-01-20 21:26:34,752 [11] WARN Rainway.Core.WebEngine.CookieMonster - Cookie Monster Failed On Pass
> 2018-01-20 22:06:04,341 [16] WARN Rainway.Core.Network.Utils.UpnP - Error Occurred During UPnP Setup: An existing connection was forcibly closed by the remote host
> 2018-01-20 22:07:15,552 [38] WARN Rainway.Core.Network.WebRTC.WebRtcSession - ICE STATE CHANGE Connected
> 2018-01-20 22:08:15,187 [38] WARN Rainway.Core.Network.WebRTC.WebRtcSession - ICE STATE CHANGE Disconnected
> 2018-01-20 22:08:15,322 [38] WARN Rainway.Core.Network.WebRTC.WebRtcSession - ICE STATE CHANGE Closed
> 2018-01-20 22:08:16,714 [47] WARN Rainway.Core.Network.WebRTC.WebRtcSession - ICE STATE CHANGE Connected
> 2018-01-20 22:09:25,697 [47] WARN Rainway.Core.Network.WebRTC.WebRtcSession - ICE STATE CHANGE Closed
> 2018-01-20 22:55:42,560 [17] WARN Rainway.Core.Windows.Api.CertificateManager - Cannot locate any certificates with distinguished name to remove: CN=ppectevhfrbbf-local.cya.gg
> 2018-01-20 22:56:37,228 [17] WARN Rainway.Core.Network.Utils.UpnP - Error Occurred During UPnP Setup: An existing connection was forcibly closed by the remote host
> 2018-01-20 22:56:44,033 [33] WARN Rainway.Core.Network.WebRTC.WebRtcSession - ICE STATE CHANGE Connected
> 2018-01-20 22:56:45,245 [20] WARN Rainway.Core.Games.AnalyzerService - Added Steam
> 2018-01-20 22:58:01,530 [17] WARN Rainway.Core.ScreenShare.ScreenShareEngine - Encoder is missing and software encoding not enabled.
> 2018-01-20 22:59:09,457 [33] WARN Rainway.Core.Network.WebRTC.WebRtcSession - ICE STATE CHANGE Disconnected
> 2018-01-20 22:59:09,491 [33] WARN Rainway.Core.Network.WebRTC.WebRtcSession - ICE STATE CHANGE Closed
> 2018-01-20 22:59:33,948 [49] WARN Rainway.Core.Network.WebRTC.WebRtcSession - ICE STATE CHANGE Connected
> 2018-01-20 22:59:54,876 [32] WARN Rainway.Core.ScreenShare.ScreenShareEngine - Encoder is missing and software encoding not enabled.
> 2018-01-20 23:02:00,552 [49] WARN Rainway.Core.Network.WebRTC.WebRtcSession - ICE STATE CHANGE Disconnected
> 2018-01-20 23:02:00,604 [49] WARN Rainway.Core.Network.WebRTC.WebRtcSession - ICE STATE CHANGE Closed
> 2018-01-20 23:02:03,013 [60] WARN Rainway.Core.Network.WebRTC.WebRtcSession - ICE STATE CHANGE Connected
> 2018-01-20 23:28:57,394 [59] WARN Rainway.Core.ScreenShare.ScreenShareEngine - Encoder is missing and software encoding not enabled.
> 2018-01-20 23:33:49,576 [17] WARN Rainway.Core.Network.Utils.UpnP - Error Occurred During UPnP Setup: An existing connection was forcibly closed by the remote host
> 2018-01-20 23:35:30,150 [16] WARN Rainway.Core.WebEngine.CookieMonster - Cookie Monster Failed On Pass
> 2018-01-20 23:41:12,304 [19] WARN Rainway.Core.Network.Utils.UpnP - Error Occurred During UPnP Setup: An existing connection was forcibly closed by the remote host
> 2018-01-20 23:41:23,110 [30] WARN Rainway.Core.Network.WebRTC.WebRtcSession - ICE STATE CHANGE Connected
> 2018-01-20 23:41:24,405 [3] WARN Rainway.Core.Games.AnalyzerService - Added Steam
> 2018-01-20 23:41:49,142 [11] WARN Rainway.Core.ScreenShare.ScreenShareEngine - Encoder is missing and software encoding not enabled.
> 2018-01-20 23:43:26,735 [16] WARN Rainway.Core.Network.Utils.UpnP - Error Occurred During UPnP Setup: An existing connection was forcibly closed by the remote host
> 2018-01-20 23:50:46,183 [17] WARN Rainway.Core.Network.Utils.UpnP - Error Occurred During UPnP Setup: An existing connection was forcibly closed by the remote host
> 2018-01-20 23:50:55,312 [37] WARN Rainway.Core.Network.WebRTC.WebRtcSession - ICE STATE CHANGE Connected
> 2018-01-20 23:50:56,206 [11] WARN Rainway.Core.Games.AnalyzerService - Added Steam
> 2018-01-20 23:51:13,815 [32] WARN Rainway.Core.ScreenShare.ScreenShareEngine - Encoder is missing and software encoding not enabled.
> 2018-01-20 23:55:22,860 [37] WARN Rainway.Core.Network.WebRTC.WebRtcSession - ICE STATE CHANGE Disconnected
> 2018-01-20 23:55:22,934 [37] WARN Rainway.Core.Network.WebRTC.WebRtcSession - ICE STATE CHANGE Closed
> 2018-01-20 23:55:44,216 [59] WARN Rainway.Core.Network.WebRTC.WebRtcSession - ICE STATE CHANGE Connected
> 2018-01-20 23:56:01,248 [12] WARN Rainway.Core.ScreenShare.ScreenShareEngine - Encoder is missing and software encoding not enabled.
> 2018-01-20 23:59:42,375 [59] WARN Rainway.Core.Network.WebRTC.WebRtcSession - ICE STATE CHANGE Disconnected
> 2018-01-20 23:59:42,398 [59] WARN Rainway.Core.Network.WebRTC.WebRtcSession - ICE STATE CHANGE Closed
> 2018-01-20 23:59:43,480 [44] WARN Rainway.Core.Network.WebRTC.WebRtcSession - ICE STATE CHANGE Connected
> 2018-01-21 00:00:00,166 [17] WARN Rainway.Core.ScreenShare.ScreenShareEngine - Encoder is missing and software encoding not enabled.
> 2018-01-21 00:01:43,245 [48] WARN Rainway.Core.Network.WebRTC.WebRtcSession - ICE STATE CHANGE Closed
> 2018-01-21 00:01:43,246 [52] WARN Rainway.Core.Network.WebRTC.WebRtcSession - ICE STATE CHANGE Closed
> 2018-01-21 00:01:43,246 [44] WARN Rainway.Core.Network.WebRTC.WebRtcSession - ICE STATE CHANGE Closed

The error is on the client, not the server.

**Comment by pianoboy8** [comment]
Would like to reply that I attempted it on firefox, and the same error occurred.
Firefox Quantum 57.0.4 (64-bit)

**Comment by tonydaexpert** [comment]
I also have this issue

**Comment by healingbrew** [comment]
Temporary workaround:

- Open your cache folder (via the rainway tray icon, if  that fails use `C:\Windows\System32\config\systemprofile\AppData\Roaming\RainwayInc\Server`)
- Open `settings.json` in a text editor
- Find `"UseSoftwareEncoding": false,`
- Change that into `"UseSoftwareEncoding": true,`

**Comment by pianoboy8** [comment]
Thanks again so much for helping me though!

**Comment by healingbrew** [comment]
This is fixed in the latest Rainway version.
