### ISSUE TITLE
update?

### ISSUE THREAD

**Issue by sakshamgoyal01** [RainwayApp/bug-tracker#304]
waiting on an update on my issue. it has been weeks
https://github.com/RainwayApp/bug-tracker/issues/272

**Comment by StackDoubleFlow** [comment]
This needs to get fixed

**Comment by lynn** [comment]
Hey there, our developers are still investigating this issue, but it remains elusive. We promise we'll let you know once we find out what's up with this, but for now we'd like to limit discussion to #272! Thanks for understanding.
