### ISSUE TITLE
Game not recognized by Rainway

### ISSUE THREAD

**Issue by DJMarramiau** [RainwayApp/bug-tracker#305]
The games "Call of Duty: Modern Warfare Remastered - Multiplayer" and "Call of Duty: Modern Warfare Remastered" doesn't get recognized by the App, Server.log file says: 2019-03-20 23:55:41,562 [32] WARN Rainway.Core.Network.Http.Utils.RainwayApiHelper - Call of Duty: Modern Warfare Remastered - Multiplayer is missing metadata! Platform ID: 393100, Platform: Steam.

OS: Windows 10 Pro 64 bits.

**Comment by neptuwunium** [comment]
Should be fixed, please refresh your library.
