### ISSUE TITLE
Web client: Unable to connect to Rainway by websocket: Couldn't resolve DNS

### ISSUE THREAD

**Issue by BagelCo** [RainwayApp/bug-tracker#31]
Host pc runs Rainway, web client only temporarily establishes connection to host PC and will lose connection mid game. This is followed by a lengthy period of time where it fails to connect back to the host pc and gives the same "Unable to connect to Rainway by websocket: Couldn't resolve DNS" error every reload. Same is true using other communication method.

Laptop running client was able to make connection through Wifi router... but temporarily.
Laptop running client was able to make connection through host PC's hotspot connection... but temporarily.

Sometimes leaving the client open will establish a connection and work for a set amount of time before disconnecting and failing to connect again. 
Laptop running client has a steady, full bars connection to wifi and loads internet fine otherwise. 

Rebooting host computer or deleting Rainway cache only sometimes alleviates the issue.

EDIT: Found out that simply exiting out of Rainway and restarting with admin privileges allows it to connect once again to client. This is a temp fix as it returns after losing connection and closing game.

**Comment by Zenexer** [comment]
Wait a minute or two after launching Rainway before visiting play.rainway.io.

**Comment by BagelCo** [comment]
No dice. It's a toss-up whether I try connecting right away or wait several minutes. I can't pinpoint what might be triggering it at all

**Comment by shirbr510** [comment]
might be related to #9 ?
