### ISSUE TITLE
Scrolling with trackpad causes scrolling to be heavily multiplied

### ISSUE THREAD

**Issue by mmccall0813** [RainwayApp/bug-tracker#318]
# Title
Scrolling is multiplied when using a trackpad
## It did/did not work in a previous version
Unsure
## Some description
I use rainway with a Chromebook and I'm almost unable to scroll without hitting the bottom of the page when using the trackpad.
## Steps

- Use Rainway on a laptop (might only happen on Chromebook)
- connect to host
- use remote desktop or launch a game then alt-tab
- scroll on a webpage or long document, etc.

## What happens

Scrolling is HEAVILY multiplied or at least tons faster than normal.

## What is expected

Normal, smooth scrolling.

## Host

 - OS: Windows 10
 - Version: Unsure
 
## Browser

 - OS: Chrome OS
 - Version: Version 72.0.3626.122 (Official Build) (64-bit)
 - Browser: Google Chrome
 - Browser Version: Unknown, cant find it anywhere

**Comment by mmccall0813** [comment]
After playing around with scrolling a bit more, it seems to only happen when I scroll down.

**Comment by lynn** [comment]
This is happening for the same reason as #297, so I'm closing this as a duplicate and tracking it there.

Basically, your trackpad has a notion of "how fast to scroll", but Rainway doesn't — even the slightest scroll event gets translated to a pretty huge one when we send it to your host PC, so the scrolling becomes erratic.

We know what to do about it! But it isn't so simple. We'll let you know once we've tackled the issue.
