### ISSUE TITLE
DMC5 Game Panel Incorrect

### ISSUE THREAD

**Issue by PsiLupan** [RainwayApp/bug-tracker#324]
In the game selection window, Devil May Cry 5 incorrectly shows the image for DmC: Devil May Cry and the mouse-over game footage is also from DmC.

The mouse-over text, however, does list the game as Devil May Cry 5.

**Comment by apecoraro** [comment]
This seems similar to #271 and #305, but probably different enough to be considered a separate bug.

**Comment by PsiLupan** [comment]
In this case, it was from Steam as well, since I forgot to mention that.

**Comment by neptuwunium** [comment]
Should be fixed, refresh your games.
