### ISSUE TITLE
Wake-On-Lan Port Still Forwarded

### ISSUE THREAD

**Issue by JTTM** [RainwayApp/bug-tracker#328]
A user in the Discord mentioned that Rainway still UPnP forwards the Wake-On-Lan port: UDP 9. Rainway removed Wake-On-Lan support in 1.0 because it didn't work for most users. It would be a good idea to stop forwarding this port since it's not used and some users might think of it as a security risk.

**Comment by BetaLeaf** [comment]
Agreed. In the mean time, users can use Windows Firewall to create an
inbound rule that blocks udp port 9. Will provide visual tutorial upon
request. Just mentioned me in a comment.

**Comment by healingbrew** [comment]
Should be fixed next update.
