### ISSUE TITLE
Roadmap Navigation Button still on website

### ISSUE THREAD

**Issue by wesd02** [RainwayApp/bug-tracker#334]
# Title

The Roadmap Navigation Button is still on the website. When I click on it, a 404 Error occurs.

![Uploading A604272B-4190-4E3D-9ADA-903C24BC64CC.png…]()

**Comment by agentd00nut** [comment]
Not sure about that one, the image isn't loading for me but i can confirm that the link shouldn't be displayed.

Could you try and do a hard refresh of the webpage ( ctrl+shift+r ) which should clear your cache of the page and reload it and respond with if the link is still present or not?

**Comment by wesd02** [comment]
I just did a hard refresh and the link went away, sorry for the confusion.
