### ISSUE TITLE
This is a test bug.

### ISSUE THREAD

**Issue by agentd00nut** [RainwayApp/bug-tracker#346]
# Title

It did/did not work in a previous version

Some description

## Steps

- Open the thing
- Edit the thing

## What happens

What happens

## What is expected

What you expected to happen

## Host

 - OS: [e.g. Windows 10 Pro]
 - Version: [e.g. 8115]
 
## Browser

 - OS: [e.g. macOS Mojave]
 - Version: [e.g. 10.14.1b]
 - Browser: [e.g. Firefox Quantum]
 - Browser Version: [e.g. 62]

**Comment by AetherCollective** [comment]
This is a test comment.
Lel

**Comment by BetaLeaf** [comment]
This is a test comment.
Lel
