### ISSUE TITLE
Rainway does not start minimized when Start Minimized is enabled

### ISSUE THREAD

**Issue by riverar** [RainwayApp/bug-tracker#352]
Rainway app version 1.0.13.0
Windows 10 1903 18362.1

Repro:
1. Start Rainway
2. Navigate to Windows Settings and ensure Start Minimized is enabled
3. Shutdown Rainway
4. Start Rainway
5. Note Rainway window still appears and takes focus

**Comment by RDCH106** [comment]
I report the same problem:

![imagen](https://user-images.githubusercontent.com/1483414/70868596-83765000-1f82-11ea-882e-3002fa1b03d4.png)

**Comment by silentcovenant** [comment]
Same here.. it's really annoying

**Comment by RDCH106** [comment]
It seems to work again

**Comment by andrewmd5** [comment]
fixed
