### ISSUE TITLE
Rainway disables mouse pointer precision on launch, doesn't re-enable

### ISSUE THREAD

**Issue by riverar** [RainwayApp/bug-tracker#359]
Rainway app version 1.0.15.0
Windows 10 1903 18362.263

Dupe of #287, however it's important this be considered as a **bug**, not an enhancement. This silently modifies system state at app start and can be very confusing to users when mouse precision is suddenly lost. I find myself _fixing_ this an uncountable number of times a day during my Rainway usage/testing.

Expected: Rainway changes this option at stream start and reverts its changes at stream end.

![image](https://user-images.githubusercontent.com/475132/62830644-e0be5700-bbc6-11e9-84df-5ab8c6f5b08c.png)

**Comment by andrewmd5** [comment]
Was closed by an a commit! 

I've fixed this behavior and it will be released in 1.0.16.0. 

- Pointer info is saved into settings. 
- Mouse acceleration is only disabled during the stream. 
- Your pointer settings will be restored on stream end.

We will also apply the last saved pointer info on startup (just in case say it crashed while you're streaming,) and shutdown. a side effect here is we do not poll for changes to these settings, so they could become out of sync, but most users don't alter their pointer often.

**Comment by andrewmd5** [comment]
Fixed in the last update, if you can verify.

**Comment by riverar** [comment]
@Codeusa Verified in 1.0.16.0
