### ISSUE TITLE
rainway host software crashes every time I try to play BeamNG Drive

### ISSUE THREAD

**Issue by mmccall0813** [RainwayApp/bug-tracker#360]
It did work in a previous version

When I try to play BeamNG drive on the Rainway Client, the host software crashes

## Steps

- open beamng
- load up a map
- host crashes

## Host

 - OS: Windows 10 Home
 - Version: Unsure
 
## Browser

 - OS: ChromeOS
 - Version: Version 75.0.3770.144 (Official Build) (64-bit)
 - Browser: Google Chrome
 - Browser Version: Chrome 75
 
## Logs
none

**Comment by AetherCollective** [comment]
Hello. My name is BetaLeaf. I noticed you missed some important info in your initial post. Please add this information so the developers will be able to better help you.

## Host Version
To get the Host Version, right click on the Start Menu, select `Run` from the list, type `winver` and select `OK`. You will see a string similar to mine.
![image](https://user-images.githubusercontent.com/7028351/63872159-537f4e80-c98b-11e9-9e61-7bf9f851e108.png)

## Logs
Before collecting logs, please shut down Rainway by right-clicking on the tray icon and selecting `Exit` from the list.

Rainway Logs are found at `%LocalAppData%\Rainway, Inc\Server\Logs`. You can simply copy-paste this string into File Explorer's address bar or right click on the Start Menu, select `Run` from the list, paste the string in the box and select `OK`. Find the most recent file and attach it in your next reply.

**Comment by mmccall0813** [comment]
Thanks, @BetaLeaf, I will definitely update my post when I get home today.

**Comment by mmccall0813** [comment]
No longer have this issue
