### ISSUE TITLE
No Games Found?

### ISSUE THREAD

**Issue by LilH3ro** [RainwayApp/bug-tracker#40]
I have been trying for a while now to get games showing in the client but it just says no games found. Ive tried reinstalling it aswell...

Also gotta note that i have all my games spread over different harddrives

**Comment by thederp** [comment]
One temporary solution may be to re-add the game as a "Non-Steam Game".

**Comment by LilH3ro** [comment]
![screenshot_3](https://user-images.githubusercontent.com/20781099/35200339-91e23e9e-ff0c-11e7-82f4-26cb2b3b4cab.png)

I tried that but doesnt seem to detect that either, but i have a feeling the software cant handle alot of games ;P

**Comment by jimmeldrum** [comment]
I only have 3 games: Quantum Break SW BF II, & Rayman Legends and the Rainway server/client doesn't detect any of them :-(

**Comment by healingbrew** [comment]
Should be fixed
