### ISSUE TITLE
Rainway Gametracker thumbnails bug

### ISSUE THREAD

**Issue by TheMulti0** [RainwayApp/bug-tracker#42]
Some games don't have a thumbnail, and have a black wallpaper instead / the game's title.
Hovering on those games icons shows the wallpaper, but when leaving them (when mouse stops hovering) they're back to black / title.
I pressed the refresh button at the top right, didn't help.
Client is Windows 10 FCU @ Chrome 64.
I got some gif's to show the situation
![GIF](https://i.imgur.com/mpVhBEF.gif)
![GIF](https://i.imgur.com/Z5u4RPG.gif)
![GIF](https://i.imgur.com/ugyKdyv.gif)

**Comment by healingbrew** [comment]
Closing in favor of #14
