### ISSUE TITLE
Some Steam Games and Non Steam games do not appear in web client.

### ISSUE THREAD

**Issue by Masterof2D** [RainwayApp/bug-tracker#47]
Some games I have on Steam and games I have added on Steam which are not Steam games do not show up in the web client. For example, I added Super Smash Flash 2 to my Steam library but it did not show up. I also have Nights into Dreams which is a Steam game also not show up.

**Comment by TheMulti0** [comment]
Same, JC3 not showing up (it's bought)

**Comment by healingbrew** [comment]
Please reply these things to #14
