### ISSUE TITLE
Unable to install rainway without WindowsMediaPlayer

### ISSUE THREAD

**Issue by healingbrew** [RainwayApp/bug-tracker#5]
source: discord

**Comment by Codeusa** [comment]
Hard requirement https://www.microsoft.com/en-us/download/details.aspx?id=48231

**Comment by healingbrew** [comment]
reopened, have multiple reports of people with Windows 10 Pro (non N/KN) having this issue with it enabled in optional features.

**Comment by healingbrew** [comment]
Solution: install Windows Media Player by going to the Windows 10 settings window and going to Apps -> Add a Feature -> Manage Optional Features

**Comment by dmnc-net** [comment]
But why is this required? I found Rainway and want to try it but I'm not interested in such software which depends on crap like Windows Media Player.
