### ISSUE TITLE
Describe the issue

### ISSUE THREAD

**Issue by progranadegrinder** [RainwayApp/bug-tracker#60]
Bug ID: 9f93a266-224b-4c78-8605-0960b2684c13
Steps to reproduce the problem:

What is the expected behavior?

What went wrong?

Did this work before?

Does this work in other browsers?

OS Info: Windows 10 Professional x64 [10.0.16299]

Rainway Server Version: 0.1.6.0

Rainway Frontend Version: 1.0.1.0

**Comment by healingbrew** [comment]
Will close in 48 hours if no response.
