### ISSUE TITLE
Missing Steam Games

### ISSUE THREAD

**Issue by thederp** [RainwayApp/bug-tracker#61]
For some reason "**PAYDAY 2**" and "**The Walking Dead Season 2**" aren't showing up.
This isn't a Steam Game, however **Watch_Dogs** does not show up on Rainway. I have the game on UPlay.

_The "solution" is to add the games as "Non-Steam Game" even though the two mentioned are Steam games._

Reasons why may be because I redeemed the games via Steam Key and/or the games were gifted to me.

Yes, I have updated Rainway + Cache Reset. I did also click on the refresh symbol on Rainway.
This was happening on the previous versions. Its been happening from the start even after updates.
My OS is Windows 10. I am up-to-date with all Windows updates, I do have the Fall Creators Update.
No extensions are enabled on Rainway's site aside for a custom scrollbar and image upload/screenshot.
No errors, the aforementioned games just don't show up.

![steamgames](https://user-images.githubusercontent.com/5713315/35200145-c88c2a8a-fed6-11e7-9ab2-bc6ac03f85b1.PNG)

**Comment by TheMulti0** [comment]
Jc3 missing aswell

**Comment by Jessomadic** [comment]
I am missing WOW but I have OverWatch so I know it's scanning battle.net. I also am missing destiny 2 but I don't really give a crap about that

**Comment by swoleguru** [comment]
Everything is up to date and no games will appear for me

**Comment by swoleguru** [comment]
I have steam and non steam games on my pc

**Comment by healingbrew** [comment]
Closing in favor of #14
