### ISSUE TITLE
Primary/Secondary accounts somehow linked on host PC? Possible Certificate issue.

### ISSUE THREAD

**Issue by ScorelessPine** [RainwayApp/bug-tracker#66]
I have two accounts with Rainway that I am using currently, the first one, ScorelessPine, for personal use, and the second one, RWTestaccount, obviously meant for testing long range streaming with a friend. I am using the same Steam account for both Rainway accounts, and I am on the latest server version.

Steps:
I was logged in to my primary account, so I logged out and logged into my secondary one. I then went to the client and attempted to log into the secondary account, but there was an error. I then logged into the client on my _primary_ account, and it connected me to my server hosted by my secondary account, which should never happen. I then logged out of everything, deleted the cache, and tried "first time setup" with my secondary account, but I received the same results as above.

Results:
Primary account client able to connect to server hosted by secondary account, but secondary account client not able to connect to that same server.

After attempting another time after deleting the cache, now neither account is able to connect to either server host account. I will continue to test and update if anything else happens.

**Comment by Codeusa** [comment]
Every time you do this you're moving your hardware bound token to the other account. Rainway does not support having more than one account attached to a PC.

**Comment by ScorelessPine** [comment]
But deleting the cache and re-starting setup should theoretically allow me to use a different account, no? At this point, neither account is able to connect to its own host, which imo seems like something different anyway. Because of this behavior, though, it seems as though if I do initial setup with one account on host, log out and log into a different account on host, then I can connect to that computer using the original account info on client, it lets me do it, while being connected to two separate accounts on client and host.

**Comment by Codeusa** [comment]
@ScorelessPine No, because we are always going to get the same hardware token for that machine.

Are you connecting over WebRTC?

**Comment by ScorelessPine** [comment]
Preferred communication method is WebRTC on my account, yes.

**Comment by Codeusa** [comment]
@healingbrew Thunderstorm is caching user info, we need to remove this -- its a hold over from debug, we should always be refetching on connection.

**Comment by ScorelessPine** [comment]
@Codeusa Wait, is that Lightning Bolt symbol supposed to be on the Server? No, I don't see that, my host shows a world icon and a snes controller icon, I'm assuming that means I'm actually using websocket. Sorry, I responded before I saw your edit. I have preferred communication method on the client set to WebRTC.

**Comment by Codeusa** [comment]
The lighting bolt symbol on the client indicates which connection method you are using, which is WebRTC. A websocket would be a wall socket icon.

**Comment by ScorelessPine** [comment]
At the moment, I'm unable to connect with either through the client. I've tried deleting the cache multiple times and restarting first time setup, but I am unable to connect right now.

**Comment by Codeusa** [comment]
Right, I'm just asking what you connected with before.

**Comment by ScorelessPine** [comment]
Yes, it was WebRTC when I encountered the bug.

**Comment by healingbrew** [comment]
should be fixed, respond if it isn't.
