### ISSUE TITLE
audio codec not suppoted

### ISSUE THREAD

**Issue by PHPJosh** [RainwayApp/bug-tracker#67]
Yes I got streaming working on xbox via edge using websockets instead of WebRTC but get the message that audio codec not supported. so my suggestion is to use MP3 for the codec as it is supported by the main browsers on every OS if the OS has the support built in or installed.

**Comment by Codeusa** [comment]
While we do have AAC support, MP3 is not suitable for streaming and as a result we will not implement it. 

That being said, our native Xbox One client will support our current codec.
