### ISSUE TITLE
Rainway Control Panel will log out and log back in at random intervals

### ISSUE THREAD

**Issue by ShadeOfTyranny** [RainwayApp/bug-tracker#7]
When the Rainway Control Panel is minimized (whether in the process of setting up the server or when fully logged in), it will seemingly at random log back out, bring the Rainway Control Panel into focus, and then automatically log back in. When fully logged in, a "Session Expired" message will appear, but when in the process of setting up the server, no such message will appear. In both scenarios, when the Rainway Control Panel automatically logs back in, it will return instantly to what it was previously doing, whether that was setting up the server or the Control Panel menu.

**Comment by BetaLeaf** [comment]
I also have this issue. I just assumed it was something on the server end revoking all sessions so I ignored it but it keeps happening.

**Comment by Codeusa** [comment]
@BetaLeaf every update revokes the session.

**Comment by BetaLeaf** [comment]
Figured as much. Thanks for confirming that.
