### ISSUE TITLE
Rainway API status site

### ISSUE THREAD

**Issue by IkeKap** [RainwayApp/bug-tracker#70]
It could use a similar one to the one that discord currently [uses](https://www.statuspage.io/?utm_source=inapp&utm_medium=powered-by&utm_campaign=status.discordapp.com&utm_content=status-pages). Apparently they offer a free trial.

This is another enhancement, but I thought that it would be a good idea to have a dedicated site to display to the end user whether or not there are widespread issues versus just people spamming in the discord.

**Comment by Zenexer** [comment]
Statuspage.io is hella expensive, and the control panel is the clunkiest thing since Vista.

**Comment by Codeusa** [comment]
@healingbrew Don't we already have this internally? We just need to slim it down and make it public facing.

**Comment by healingbrew** [comment]
No but I can create one with Viet's work.
