### ISSUE TITLE
Software Encode Broken?

### ISSUE THREAD

**Issue by MrPokeboy8** [RainwayApp/bug-tracker#73]
Rainway 0.1.9 no longer works with software encoding compared to 0.1.6.
When the client tries to connect, black shows for a few seconds and it ejects back to the game list.

I already tried restarting the host and clearing cache.

Though, I'd have to imagine that getting the delay issue fixed is a higher priority than this :P

**Comment by Codeusa** [comment]
Confirmed, will be fixed shortly.

**Comment by Codeusa** [comment]
Fixed
