### ISSUE TITLE
Unrecognized games shown as 'The Egyptian Prophecy'

### ISSUE THREAD

**Issue by azumukupoe** [RainwayApp/bug-tracker#77]

**Comment by trilleplay** [comment]
Please provide more details so this issue can be triaged.

**Comment by azumukupoe** [comment]
@trilleplay It's the non-steam games such as emulators.

**Comment by Jessomadic** [comment]
The Egyptian Prophecy is being used as a placeholder for some reason.(It also has become the first meme of rainway see the discord pins)

**Comment by azumukupoe** [comment]
@Jessomadic I see. But I think it makes people confused.

**Comment by Jessomadic** [comment]
@azumukupoe I can see why that would happen. I think they are working on a fix. But they are going to be using this game in their Live Stream Test so they might clear it up then

**Comment by BetaLeaf** [comment]
same

**Comment by rriilleeyyyy** [comment]
FiveM the GTA V mod came up as The Egyptian Prophecy.

**Comment by healingbrew** [comment]
Please comment with all invalid banners on #14
