### ISSUE TITLE
rainway in android chrome browser

### ISSUE THREAD

**Issue by neslo18** [RainwayApp/bug-tracker#79]
the stream has terrible latency on android chrome browser but runs fine on another laptop or desktop

**Comment by JTTM** [comment]
Rainway is not fully supported on Android. Please wait until the official app launches for Android in the next few weeks.

**Comment by neslo18** [comment]
Well this is supposed to work on any device in browser so this should be fixed at least at some point....oh well....

**Comment by JTTM** [comment]
Rainway officially supports Desktop Chrome and Firefox. It may work in other situations, but mobile devices and consoles will not be officially supported or worked on until apps come for them.
