### ISSUE TITLE
The SSL certificate used to load resources from https://steamcdn-a.akamaihd.net will be distrusted in the future.

### ISSUE THREAD

**Issue by BetaLeaf** [RainwayApp/bug-tracker#84]
The SSL certificate used to load resources from https://steamcdn-a.akamaihd.net will be distrusted in the future. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.

Found error using Dev Tools and inspecting Control.rainway.io/(index) on line 1

**Comment by Jessomadic** [comment]
Is there an oh shit tag?

**Comment by BetaLeaf** [comment]
Firefox has it's own set of issues. For me, firefox has a really small frame so its hard to see anything.
![image](https://user-images.githubusercontent.com/7028351/35227029-f20d01f2-ff5a-11e7-9ccb-433956569083.png)

**Comment by Jessomadic** [comment]
Interesting I had this issue once before and it went away by itself.

**Comment by BetaLeaf** [comment]
yea it happened to me on both firefox stable and nightly

**Comment by Jessomadic** [comment]
Strange. Have you made an issue so they know? That way there is not two issues they have to deal with in one thread

**Comment by BetaLeaf** [comment]
I let the CEO know. Lets try to remain on topic. I'm on discord if you want to chat.

**Comment by Jessomadic** [comment]
Cool see you there

**Comment by Codeusa** [comment]
This is on Valve and there is nothing we can do about it.

**Comment by BetaLeaf** [comment]
Alright, I was just reporting it. I doubt there was anything you could do about it.
I'm sure you already know, but rainway is down and discord is lit up atm. @Codeusa
