### ISSUE TITLE
Add a way to tell similar displays apart.

### ISSUE THREAD

**Issue by Eskildybvik** [RainwayApp/bug-tracker#86]
I have two identical monitors, so when I'm going to select one of them, it's not easy to know what display is the correct one. 
![image](https://user-images.githubusercontent.com/22179929/35229504-e2f43aee-ff93-11e7-8ec6-8f697862363c.png)

**Comment by Jessomadic** [comment]
You can do this by going to the display settings in windows. Display 1 will be your main display. It has a picture if that is on your left or on you right (or up and down if you have it set up that way)

**Comment by NicholasG04** [comment]
Fake news! My main display is display 2. But yes, you can check from inside Windows Settings.

**Comment by healingbrew** [comment]
Added in a recent update, during the setup screen you'll have a snapshot of each monitor to select.
