### ISSUE TITLE
Open Cache Folder button opens to wrong folder.

### ISSUE THREAD

**Issue by BetaLeaf** [RainwayApp/bug-tracker#87]
When right clicking Rainway in the tray and selecting Open cache folder, it attempts to open
```%UserProfile%\AppData\Roaming\RainwayInc\Server``` 
Should be:
```%SystemRoot%\System32\config\systemprofile\AppData\Roaming\RainwayInc\Server```

**Comment by BetaLeaf** [comment]
Just updated to the latest version announced on discord today at 10:19 AM (EST) and confirmed still opens to the wrong path. This still needs fixed.

**Comment by BetaLeaf** [comment]
Just updated to the latest version (0.1.15) and confirmed still opens to the wrong path. This still needs fixed.

**Comment by BetaLeaf** [comment]
Just updated to the latest version (0.1.16) and confirmed still opens to the wrong path. This still needs fixed.

**Comment by Codeusa** [comment]
Fixed

**Comment by BetaLeaf** [comment]
Thanks!
