### ISSUE TITLE
Game is displayed in a small box

### ISSUE THREAD

**Issue by EpicKnarvik97** [RainwayApp/bug-tracker#93]
Streaming from a 1080p laptop to a 1366 x 768 laptop (not tested on other systems), opens games in a box less than 700 x 400 px. This does not change depending on which resolution scaling (or none) I set.

I also sometimes get this error, which may be relevant:

> Unhandled exception!
> 
> An error occurred:
> IndexSizeError: Index or size is negative or greater than the allowed amount
> The Rainway team has been notified and is undoubtedly working on a solution.

**Comment by healingbrew** [comment]
Duplicate of #18
