### ISSUE TITLE
WebSocket Certificate relies on port 443 to be open

### ISSUE THREAD

**Issue by JTTM** [RainwayApp/bug-tracker#99]
Port 443 is a common port for webservers on the https connection and some people like me may have a webserver running on their home network. An external connection to Rainway can't be made when this happens. 

I would recommend something like 8443 or even random be used for the certificate. So there is no conflicts between Rainway and web servers.

**Comment by Codeusa** [comment]
Used to bypass firewalls.

**Comment by danmademe** [comment]
You should be doing a check before writing rules to upnp... a simple scan of the localnet would have shown services on port 443.. 

Also it took me a while to figure why my certs were getting hijacked by a cert from cya.gg ... I had told rainway not to start at boot, but your auto updater decided to ignore that.

You can handle this so much better than you have.. you're not bound to 443, @JTTM has a point..

**Comment by JTTM** [comment]
They have fixed this now by adding a fallback port for websockets. To see more info join the Rainway Discord and see the pinned message in #support.
